version: "3.8"
services:

  mysql-db:
    image: mysql:latest
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: f4x4d8p6
      MYSQL_DATABASE: metabase
      MYSQL_USER: metabase
      MYSQL_PASSWORD: f4x4d8p6

  metabase-app:
    image: metabase/metabase
    restart: unless-stopped
    container_name: metabase-app
    ports:
      - "3001:3000"
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: f4x4d8p6
      MB_DB_HOST: mysql-db
#      MB_DB_HOST: dhiego-lifebook-a357
  #    depends_on:
  #      - mysql-db
  #    links:
  #      - mysql-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    container_name: phpmyadmin
    #    links:
    #      - mysql-db
    environment:
#      PMA_HOST: mysql-db
      PMA_HOST: dhiego-lifebook-a357
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8185:80"

  chrome:
    image: selenium/node-chrome:latest
    restart: unless-stopped
    shm_size: 2gb
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    restart: unless-stopped
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    ports:
      - "3002:3000"

  drawio:
    image: jgraph/drawio:latest
    restart: unless-stopped
    container_name: drawio
    ports:
      - "3003:8080"

  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - "3004:3000"
    restart: unless-stopped

  ubuntu:
    image: kasmweb/ubuntu-jammy-desktop:latest
    restart: unless-stopped
    shm_size: 512m
    container_name: ubuntu
    environment:
      - VNC_PW=f4x4d8p6
    ports:
      - "3005:6901"